kind: Service
apiVersion: v1
metadata:
  name: api-ksr-service
  labels:
    app: api-ksr
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api-ksr