kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: eliott-route
  labels:
    app: eliott
spec:
  to:
    kind: Service
    name: eliott-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
