kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: api-its4u-route
  labels:
    app: api-its4u
spec:
  to:
    kind: Service
    name: api-its4u-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
