kind: Service
apiVersion: v1
metadata:
  name: api-its4u-service
  labels:
    app: api-its4u
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api-its4u