kind: Service
apiVersion: v1
metadata:
  name: student-api-service
  labels:
    app: student-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: student-api