kind: Service
apiVersion: v1
metadata:
  name: testksc-service
  labels:
    app: testksc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: testksc