apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-its4u
  namespace: openshift-gitops
spec:
  destination:
    namespace: lab-workspace
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: api-its4u/src/main/jkube
    repoURL: https://github.com/kevbrain/lab-workspace.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true