apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-1_claim
  labels:
    app: api-ctie
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-nfs-storage
---
