allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
groups:
- system:cluster-admins
kind: SecurityContextConstraints
metadata:
  name: api-ctie-scc
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
fsGroup:
  type: MustRunAs
  ranges:
  - min: 44555
    max: 44555
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 44555
  uidRangeMax: 44555
seLinuxContext:
  type: MustRunAs
supplementalGroups:
   type: MustRunAs
   ranges:
   - min: 44555
     max: 44555
users:
- system:serviceaccount:api-ctie-{{bil.environment}}:api-ctie-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
- nfs