kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: owen-route
  labels:
    app: owen
spec:
  to:
    kind: Service
    name: owen-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
