kind: Service
apiVersion: v1
metadata:
  name: api-bil-service
  labels:
    app: api-bil
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api-bil