kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    build-commit: '@git.commit.id.abbrev@'
    build-date: "@git.build.time@"
  name: ksr-api
  labels:
    app: ksr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksr-api
  template:
    metadata:
      name: ksr-api
      labels:
        app: ksr-api
      annotations:
        build-commit: '@git.commit.id.abbrev@'
        build-date: "@git.build.time@"
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          resources:
            requests:
              memory: 250Mi
              cpu : 200m
            limits:
              memory: 750Mi
              cpu : 500m
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8081
              scheme: HTTP
          env:
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          volumeMounts:
            - name: emptydirlogs
              mountPath: /Logs
          image: >-
            image-registry.openshift-image-registry.svc.cluster.local:5000/lab-workspace/ksr-api:latest
      restartPolicy: Always