kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: chat-route
  labels:
    app: chat
spec:
  to:
    kind: Service
    name: chat-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
