kind: Service
apiVersion: v1
metadata:
  name: sample-service
  labels:
    app: sample
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: sample