kind: Service
apiVersion: v1
metadata:
  name: lns-backend-2-service
  labels:
    app: lns-backend-2
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: lns-backend-2