kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ocpi-pi-route
  labels:
    app: ocpi-pi
spec:
  to:
    kind: Service
    name: ocpi-pi-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
