kind: Service
apiVersion: v1
metadata:
  name: ocpi-pi-service
  labels:
    app: ocpi-pi
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ocpi-pi