kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fullTest-route
  labels:
    app: fullTest
spec:
  to:
    kind: Service
    name: fullTest-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
